name: Check upstream vaultwarden repository

concurrency: ci-check-upstream

on:
  schedule:
    - cron: 15 2 * * *
  workflow_dispatch:

jobs:
  check-upstream-version:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Get latest versions
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        python generate-files.py

    - name: Commit any changes
      run: |
        if [[ ${VW_HAS_UPDATE} == true ]] ; then
          echo "Upstream update found."
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add vaultwarden-web-vault/debian/changelog vaultwarden/debian/changelog vaultwarden/debian/control
          git status
          git commit -m "Update to server ${VW_SERVER_VERSION} and web vault ${VW_WEB_VERSION}."
          git push
        fi

    - name: Dispatch build workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: build.yaml
